version: '{build}'
image: Visual Studio 2019
init:
  - ps: |
      If($Env:APPVEYOR_REPO_TAG -eq "true")
      {
        Write-Host "We now have a tagged release. Proper."
        Write-Host "Tag is $Env:APPVEYOR_REPO_TAG_NAME"
        $base = $env:APPVEYOR_REPO_TAG_NAME.split('-')[0]
        $arr = $base.split(".")
        $major = $arr[0]
        $minor = $arr[1]
        $patch = $arr[2]
        Update-AppveyorBuild -Version "$major.$minor.$patch.$Env:APPVEYOR_BUILD_VERSION"
        $env:CLEANTAG=$base
      } 
      else 
      {
        $releases = "https://api.github.com/repos/$env:APPVEYOR_REPO_NAME/releases"
        $tag = (Invoke-WebRequest $releases | ConvertFrom-Json)[0].tag_name
        
        $base = $tag.Split("-")[0]
        $arr = $base.split(".")
        $major = $arr[0]
        $minor = $arr[1]
        $patch = $arr[2]
        Update-AppveyorBuild -Version "$major.$minor.$patch.$Env:APPVEYOR_BUILD_VERSION-wip"
        $env:CLEANTAG=$base
      }
      Write-Host "Hello. Build version is: $Env:APPVEYOR_BUILD_VERSION; Clean Tag: $Env:CLEANTAG"

before_build:
- cmd: >-
    nuget restore SpeckleCore\SpeckleCore.sln

# version
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: $(CLEANTAG)
  assembly_version: $(CLEANTAG)
  file_version: $(CLEANTAG)
  informational_version: $(CLEANTAG)
  package_version: '{version}'


build:
  publish_nuget: true
  publish_nuget_symbols: true
  use_snupkg_format: true
  project: SpeckleCore\SpeckleCore.sln
  verbosity: minimal

deploy:
  provider: NuGet
  server:                  # remove to push to NuGet.org
  api_key:
    secure: 5avZp2CuKwWIDcMTTQhXtRWX297z/dnZraZoSeGSey8W4stBeZIm5pZU38tTmJWZ
  skip_symbols: false
  symbol_server:           # remove to push symbols to SymbolSource.org
  on:
    appveyor_repo_tag: true
notifications:
- provider: Slack
  incoming_webhook:
    secure: 9Kt/ImvGdsQ/dzmRdSaMIG+BO0R29MOJC7eZZnK5m5TyWwE+4nofEcYlb/r4lh9Z1Dx/bR+7oQtgAYO3W5s+qJshkT6Is9irYw3TfMZX7/M=
  channel: '#devtalk'
  template: Build <{{buildUrl}}|#{{buildVersion}}> (<{{commitUrl}}|{{commitId}}>) of {{repositoryName}}@{{branch}}) by {{commitAuthor}} {{status}} in {{duration}}
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true
configuration:
  - Release
